clash-tracker/main/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

clash-tracker/main/objects/Player__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <externalId>true</externalId>
    <label>Tag</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

clash-tracker/main/classes/trigger-handler/_test/PlayerTriggerHandlerTest.cls
@IsTest
private class PlayerTriggerHandlerTest {
    @IsTest
    static void testOnApplyDefaults() {
        List<Player__c> players = new List<Player__c> {
            new Player__c(Name = 'Player A', Tag__c = '#abc123'),
            new Player__c(Name = 'Player B', Tag__c = '#def456')
        };

        System.Test.startTest();
        insert players;
        System.Test.stopTest();

        List<Player__c> insertedplayers = [SELECT Id, Name, Tag__c FROM Player__c ORDER BY Name];
        for (Player__c player : insertedplayers) {
            Assert.areEqual(true, !player.Tag__c.contains('#'), 'The Tag__c field should have been stripped of a leading # character and converted to upper case');
        }
    }

    @IsTest
    static void testOnValidate() {
        insert new List<Player__c> {
            new Player__c(Name = 'Player A', Tag__c = '#abc123')
        };

        List<Player__c> insertedPlayers = [SELECT Id, Name, Tag__c FROM Player__c ORDER BY Name];
        try {
            for (Player__c player : insertedplayers) {
                player.Tag__c = 'altered';
            }
            update insertedPlayers;

            Assert.fail('Custom validation exception expected');
        } catch (Exception ex) {
            Assert.areEqual(true, ex != null, 'An exception should have been caught');
        }
    }
}