clash-tracker/main/objects/Clan__c/Clan__c.object-meta.xml
<CustomObject>
    <label>Clan</label>
    <nameField>
        <label>Clan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

clash-tracker/main/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

clash-tracker/main/objects/Player__c/fields/Clan__c.field-meta.xml
<CustomField>
    <fullName>Clan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clan</label>
    <referenceTo>Clan__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

clash-tracker/main/objects/Player__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

clash-tracker/main/objects/Player__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <externalId>true</externalId>
    <label>Tag</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

clash-tracker/main/objects/Player__c/fields/Town_Hall_Level__c.field-meta.xml
<CustomField>
    <fullName>Town_Hall_Level__c</fullName>
    <label>Town Hall Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

clash-tracker/main/classes/service/clash-api/clans/ClansServiceImpl.cls
public with sharing class ClansServiceImpl extends ClashApiService implements IClansService {
    private List<Player__c> playerRecords = new List<Player__c>();

    public void registerForTracking(List<String> clanTags) {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        // NOTE: external service does not support bulk format and multiple requests must be sent one-by-one
        for (String clanTag : clanTags) {
            setRequest(new Map<String, String> { 'tag' => clanTag.remove('#') });

            // NOTE: explicit use of 'this' for clarity; inherited from ClashApiService base class
            this.execute();
            handleServiceResponse();
        }

        IPlayers playersDomain = Players.newInstance(playerRecords);

        // TODO: ideally, support native upsert which is not part of standard fflib unit of work; extend fflib_SObjectUnitOfWork to support native upsert
        playersDomain.insertClanMembers(uow);
        uow.commitWork();

        initializeWarTracking(clanTags);
    }

    public override void setRequest(Map<String, String> argumentsByParameter) {
        // NOTE: explicit use of 'this' for clarity; inherited from ClashApiService base class
        this.request = new HttpRequest();
        request.setEndpoint('callout:Clash_API/v1/clans/%23' + argumentsByParameter.get('tag'));
        request.setMethod('GET');
    }

    public override void handleServiceResponse() {
        for (Clans.Clan c : new List<Clans.Clan> { (Clans.Clan) JSON.deserialize(this.response.getBody(), Clans.Clan.class) }) {
            addPlayers(playerRecords, c);
        }
    }

    private void addPlayers(List<Player__c> playerRecords, Clans.Clan c) {
        for (Clans.Member clanMember : c.memberList) {
            playerRecords.add(
                new Player__c(
                    Name = clanMember.name,
                    Tag__c = clanMember.tag,
                    Clan__r = new Clan__c(Tag__c = c.tag.remove('#').toUpperCase()),
                    Town_Hall_Level__c = clanMember.townHallLevel,
                    Role__c = clanMember.role
                )
            );
        }
    }

    private void initializeWarTracking(List<String> clanTags) {
        System.enqueueJob(new ClashApiService.Queued(Types.CLAN_WARS, clanTags));
    }
}