clash-tracker/main/objects/Apex_Debug_Log__c/Apex_Debug_Log__c.object-meta.xml
<CustomObject>
    <description>A debugging object that stores success or failure information related to Apex classes and web service callouts.</description>
    <label>Apex Debug Log</label>
    <nameField>
        <label>Apex Debug Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

clash-tracker/main/objects/Apex_Debug_Log__c/fields/Inbound_Message__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Message__c</fullName>
    <label>Inbound Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

clash-tracker/main/objects/Apex_Debug_Log__c/fields/Outbound_Message__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Message__c</fullName>
    <label>Outbound Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

clash-tracker/main/objects/Clan__c/Clan__c.object-meta.xml
<CustomObject>
    <label>Clan</label>
    <nameField>
        <label>Clan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

clash-tracker/main/objects/Clan_War__c/Clan_War__c.object-meta.xml
<CustomObject>
    <label>Clan War</label>
    <nameField>
        <label>Clan War Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clan Wars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

clash-tracker/main/objects/Clan_War__c/fields/Clan__c.field-meta.xml
<CustomField>
    <fullName>Clan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clan</label>
    <referenceTo>Clan__c</referenceTo>
    <relationshipLabel>Clan Wars</relationshipLabel>
    <relationshipName>Clan_Wars</relationshipName>
    <type>Lookup</type>
</CustomField>

clash-tracker/main/objects/Clan_War__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

clash-tracker/main/objects/Clan_War__c/fields/Preparation_Time__c.field-meta.xml
<CustomField>
    <fullName>Preparation_Time__c</fullName>
    <label>Preparation Time</label>
    <type>DateTime</type>
</CustomField>

clash-tracker/main/objects/Clan_War__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

clash-tracker/main/objects/Clan_War__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

clash-tracker/main/objects/Clan_War_Performance__c/Clan_War_Performance__c.object-meta.xml
<CustomObject>
    <label>Clan War Performance</label>
    <nameField>
        <label>Clan War Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clan War Performances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

clash-tracker/main/objects/Clan_War_Performance__c/fields/Attacker__c.field-meta.xml
<CustomField>
    <fullName>Attacker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attacker</label>
    <referenceTo>Player__c</referenceTo>
    <relationshipLabel>Clan War Performances</relationshipLabel>
    <relationshipName>Clan_War_Performances</relationshipName>
    <type>Lookup</type>
</CustomField>

clash-tracker/main/objects/Clan_War_Performance__c/fields/Clan_War__c.field-meta.xml
<CustomField>
    <fullName>Clan_War__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clan War</label>
    <referenceTo>Clan_War__c</referenceTo>
    <relationshipLabel>Clan War Performances</relationshipLabel>
    <relationshipName>Clan_War_Performances</relationshipName>
    <type>Lookup</type>
</CustomField>

clash-tracker/main/objects/Clan_War_Performance__c/fields/Destruction_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Destruction_Percentage__c</fullName>
    <label>Destruction Percentage</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

clash-tracker/main/objects/Clan_War_Performance__c/fields/Stars__c.field-meta.xml
<CustomField>
    <fullName>Stars__c</fullName>
    <label>Stars</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

clash-tracker/main/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

clash-tracker/main/objects/Player__c/fields/Clan__c.field-meta.xml
<CustomField>
    <fullName>Clan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clan</label>
    <referenceTo>Clan__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

clash-tracker/main/objects/Player__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <externalId>true</externalId>
    <label>Tag</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

clash-tracker/main/classes/service/clash-api/clan-wars/ClanWarsServiceImpl.cls
public with sharing class ClanWarsServiceImpl extends ClashApiService implements IClanWarsService {
    /**
     * war states enum reference:
     *      GROUP_NOT_FOUND, NOT_IN_WAR, PREPARATION, WAR, ENDED
     */
    private List<Clan_War__c> clanWarRecords = new List<Clan_War__c>();

    public void processWars(List<String> clanTags) {
        try {
            // NOTE: external service does not support bulk format and multiple requests must be sent one-by-one
            for (String clanTag : clanTags) {
                setRequest(new Map<String, String> { 'tag' => clanTag.remove('#') });

                // NOTE: explicit use of 'this' for clarity; inherited from ClashApiService base class
                this.execute();
                handleServiceResponse();
            }

            if (clanWarRecords.size() > 0) {
                fflib_ISObjectUnitOfWork singletonUow = Application.ClashTrackerUnitOfWork.getInstance();
                IClanWars clanWarsDomain = ClanWars.newInstance(clanWarRecords);
                clanWarsDomain.registerNewRecords(singletonUow);

                singletonUow.commitWork();
            }
        } catch (Exception ex) {
            String apiResponse = this.response.getBody();
            if (apiResponse.length() > 32700) {
                apiResponse = apiResponse.substring(0, 32700);
            }
            apiResponse = String.valueOf(this.response.getStatusCode()) + '\n' + apiResponse;

            // TODO: refactor according to a more robust design
            insert new Apex_Debug_Log__c(
                Name = ex.getTypeName() + ' @ ' + String.valueOf(System.now()),
                Inbound_Message__c = ex.getStackTraceString(),
                Type__c = 'Error',
                Message__c = String.valueOf(ex.getLineNumber()) + ': ' + ex.getMessage(),
                Outbound_Message__c = apiResponse
            );
        }
    }

    public override void setRequest(Map<String, String> argumentsByParameter) {
        // NOTE: explicit use of 'this' for clarity; inherited from ClashApiService base class
        this.request = new HttpRequest();
        request.setEndpoint('callout:Clash_API/v1/clans/%23' + argumentsByParameter.get('tag') + '/currentwar');
        request.setMethod('GET');
    }

    // TODO: ideally, support native upsert which is not part of standard fflib unit of work; extend fflib_SObjectUnitOfWork to support native upsert
    public override void handleServiceResponse() {
        for (ClanWars.War w : new List<ClanWars.War> { (ClanWars.War) JSON.deserialize(this.response.getBody(), ClanWars.War.class) }) {
            // NOTE: clanTag not available in response if clan is not in war; always fetch from request endpoint for consistency
            String clanTag = this.request.getEndpoint().substringBetween('%23', '/');
            String jobName = 'Check War for ' + clanTag + ' @ ';
            Datetime dt = System.now();
            Integer bufferMinutes = 1440;

            if (w.state.equalsIgnoreCase('preparation') || w.state.equalsIgnoreCase('inWar')) {
                // TODO: player tags across all clans in context should be collected before enqueuing job
                System.enqueueJob(new ClashApiService.Queued(Types.PLAYERS, getPlayerTags(w)));
                jobName = jobName.replace('Check War', 'End War');
                dt = ClashApiService.getDatetime(w.endTime);
                bufferMinutes = 2;
            } else if (w.state.equalsIgnoreCase('warEnded')) {
                finalizeClanWarPerformances(w);
            }

            scheduleNextRun(clanTag, jobName, dt, bufferMinutes);
        }
    }

    private List<String> getPlayerTags(ClanWars.War w) {
        List<String> playerTags = new List<String>();

        for (ClanWars.Member player : w.clan.members) {
            playerTags.add(player.tag.remove('#'));
        }

        return playerTags;
    }

    private void finalizeClanWarPerformances(ClanWars.War w) {
        Clan_War__c clanWar = new Clan_War__c(
            Name = w.clan.name + ' vs. ' + w.opponent.name,
            Clan__r = new Clan__c(Tag__c = w.clan.tag.remove('#').toUpperCase()),
            Preparation_Time__c = ClashApiService.getDatetime(w.preparationStartTime),
            Start_Time__c = ClashApiService.getDatetime(w.startTime),
            End_Time__c = ClashApiService.getDatetime(w.endTime),
            State__c = w.state,
            Outcome__c = getOutcome(w)
        );
        clanWarRecords.add(clanWar);

        addClanWarPerformances(w, clanWar);
    }

    private String getOutcome(ClanWars.War w) {
        return
            w.clan.stars > w.opponent.stars ? 'Win' :
            w.clan.stars < w.opponent.stars ? 'Lose' :
            w.clan.destructionPercentage > w.opponent.destructionPercentage ? 'Win' :
            w.clan.destructionPercentage < w.opponent.destructionPercentage ? 'Lose' :
            'Draw';
    }

    private void addClanWarPerformances(ClanWars.War w, Clan_War__c clanWar) {
        for (ClanWars.Member player : w.clan.members) {
            /**
             * NOTE: war roster is immutable and set prior to warEnded state; all players will exist
             */
            addPlayerClanWarPerformances(player, clanWar);
        }
    }

    private void addPlayerClanWarPerformances(ClanWars.Member player, Clan_War__c clanWar) {
        List<Clan_War_Performance__c> clanWarPerformanceRecords = new List<Clan_War_Performance__c>();

        if (player.attacks == null) {
            player.attacks = getMissedAttacks(2, player.tag);
        } else if (player.attacks.size() == 1) {
            player.attacks.addAll(getMissedAttacks(1, player.tag));
        }

        for (ClanWars.Attack attack : player.attacks) {
            clanWarPerformanceRecords.add(
                new Clan_War_Performance__c(
                    Attacker__r = new Player__c(Tag__c = player.tag.remove('#').toUpperCase()),
                    Destruction_Percentage__c = attack.destructionPercentage,
                    Stars__c = attack.stars
                )
            );
        }
        /**
         * NOTE: this seems like bad design to instantiate a new ClanWarsPerformance domain for each player
         *      singleton with ability to add more records in dynamically?
         */
        fflib_ISObjectUnitOfWork singletonUow = Application.ClashTrackerUnitOfWork.getInstance();
        IClanWarPerformances clanWarPerformancesDomain = ClanWarPerformances.newInstance(clanWarPerformanceRecords);
        clanWarPerformancesDomain.registerNewRecords(singletonUow, clanWar);
    }

    private List<ClanWars.Attack> getMissedAttacks(Integer missedAttacks, String playerTag) {
        List<ClanWars.Attack> attacks = new List<ClanWars.Attack>();
        
        for (Integer i = 0; i < missedAttacks; i++) {
            // NOTE: should probably distinguish between a true miss and 0 star / 0 percent
            ClanWars.Attack attack = new ClanWars.Attack();
            attack.attackerTag = playerTag;
            attack.destructionPercentage = 0;
            attack.stars = 0;
            
            attacks.add(attack);     
        }

        return attacks;
    }

    private void scheduleNextRun(String clanTag, String jobName, Datetime dt, Integer bufferMinutes) {
        System.schedule(
            jobName + String.valueOf(dt.addMinutes(bufferMinutes)) + ' : ' + System.UUID.randomUUID().toString(),
            CronUtility.getCronExpressionForNextScheduledJob(dt, bufferMinutes),
            new ClashApiServiceSchedulable(ClashApiService.Types.CLAN_WARS, new List<String> { clanTag })
        );
    }
}